language: java
jdk:
  - openjdk8

script:
  - ./gradlew check

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-nik-store"